version: 2.1
executors: 
  node-executor:
    - image: circleci/node:10-jessie

jobs: 
  hello-world: 
    executor:  node-executor
    steps: 
      - run: echo "hello world"


  second-job: 
    executor:  node-executor
    steps: 
      - run: echo "this is second job"

workflows:
  my-workflow:
    jobs:
      - hello-world
      - second-job

