version: 2.1
executors:
  my-executor: 
    docker:
      - image: ubuntu-1604:201903-01

jobs:
  build:
    executor: my-executor
    steps:
      - run: echo "A first hello"
  # two:
  #   executor: my-executor
  #   steps:
  #     - run: echo "A more familiar hi"
