version: 2.1
executors:
  my-executor:
    machine:
      image: ubuntu-1604:201903-01
    # docker:
    #   - image: circleci/node:12.1-stretch


commands:
  my-command:
    description: 'this is my command'
    steps:
      - run: echo 'my-command is called'
          

jobs:
  build:
    executor: my-executor

    steps:
      - run: echo "A first hello"

  test:
    executor: my-executor
    steps:
      - run: echo "test job is called"
