version: 2.1
executors: # define execution environment for jobs
  my-executor:
    docker: 
      - image: circleci/node:12.1-stretch 

commands:
  my-command:
    description: 'this is my command'
    steps:
      - run: echo 'my-command is called' 
          

jobs:
  build:  # define circleci default entrypoint job: build
    executor: my-executor  # use predefined executor
    parallelism: 2         # run this job in 2 containers in parallel
    environment:           # define environment variables for job: build
      Foo: 'bar'

    steps:               # define exact task to be executed in job : build
      - run: echo "A first hello" 
      - run: echo $Foo 
      - run:
          name: Running tests
          command: echo "make test"
      - checkout
      - run: ls
          

  myjob:
    environment:
      RUN_WHEN: true
    parameters:
      preinstall-foo:
        type: boolean
        default: false
      run_when_step:
        type: env_var_name
        default: WHATEVER

    executor: my-executor
    steps:
      - run: echo "preinstall is << parameters.run_when_step >>"
      - when:
          condition: << parameters.run_when_step>>
          steps:
            - run: echo "preinstall"


workflows:
  workflow:
    jobs:
      - build
      - myjob:
          run_when_step: RUN_WHEN



