version: 2.1
executors: # define execution environment for jobs
  my-executor:
    docker: 
      - image: circleci/node:12.1-stretch 

commands:
  my-command:
    description: 'this is my command'
    steps:
      - run: echo 'my-command is called' 
          

jobs: 
  myjob:
    environment:
      RUN_WHEN: true
    parameters:
      preinstall-foo:
        type: boolean
        default: false
      run_when_step:
        type: env_var_name
        default: WHATEVER

    executor: my-executor
    steps:
      - run: echo "preinstall is << parameters.run_when_step >>"
      - when:
          condition: << parameters.run_when_step>>
          steps:
            - run: echo "preinstall"
      - run: |
          if [ ! -d ~/workspace/ ]; then
            mkdir -p ~/workspace/
          fi

          echo "111"  >> ~/workspace/info
      - persist_to_workspace:
          root: '~/workspace'
          paths: *

  my_second_job:
    executor: my-executor
    steps:
      - run: echo 'second job is running' 
      - attach_workspace: 
          at: '~/workspace' 
      - run: cat '~/workspace/info'
          



workflows:
  workflow:
    jobs:
      - myjob:
          run_when_step: RUN_WHEN
      - my_second_job:
          requires:
            - myjob
