version: 2.1
executors: # define execution environment for jobs
  my-executor:
    docker: 
      - image: circleci/node:12.1-stretch 

commands:
  my-command:
    description: 'this is my command'
    steps:
      - run: echo 'my-command is called' 
          

jobs:
  build:  # define circleci default entrypoint job: build
    executor: my-executor  # use predefined executor
    # parallelism: 2         # run this job in 2 containers in parallel
    environment:           # define environment variables for job: build
      Foo: 'bar'

    steps:               # define exact task to be executed in job : build
      - run: echo "A first hello" 
      - run: echo $Foo 
      - run:
          name: Running tests
          command: echo "make test"
      - checkout
      - run: ls
          

  myjob:
    parameters:
      preinstall-foo:
        type: boolean
        default: false
    executor: my-executor
    steps:
      - run: echo "preinstall is << parameters.preinstall-foo >>"
      - when:
          condition: << parameters.preinstall-foo >>
          steps:
            - run: echo "preinstall"
      - unless:
          condition: << parameters.preinstall-foo >>
          steps:
            - run: echo "don't preinstall"


workflows:
  workflow:
    jobs:
      - build
      - myjob:
          preinstall-foo: false
      - myjob: 
          preinstall-foo: true



